slack:
  token: <Slack OAuth token>
  channel_id: <ID of Slack channel to post in> # Note: Slack must have post access to the channel

host_monitor:
  sleep_time: <Time to sleep between checking host state>
  hosts:
    host_type_name:
      username: <IPMI username for these hosts>
      password: <IPMI password for these hosts>
      hosts:
        - <IP Addresses of hosts>
        - <Yet another ip with the same credentials>
    another_host_type:
      username: <Different IPMI username>
      password: <Different IPMI password>
      hosts:
        - <IP Address or host name for different hosts>
    m1000e:
      username: <CMC username>
      password: <CMC password>
      chassis: <CMC IP or hostname>
      fan_threshold: <Fan RPM at which to begin sending alerts>
      hosts:
        - <IPMI IP addresses or hostname>
  